"""Add sidequest core properties

Revision ID: 0003
Revises: 0002
Create Date: 2026-02-28 19:51:07.950551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sidequests', sa.Column('description', sa.String(), nullable=True))
    op.add_column('sidequests', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('sidequests', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'sidequests', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sidequests', type_='foreignkey')
    op.drop_column('sidequests', 'user_id')
    op.drop_column('sidequests', 'completed_at')
    op.drop_column('sidequests', 'description')
    # ### end Alembic commands ###
