"""add_sidequest_reward_xp

Revision ID: 728c5cb63728
Revises: d83f1c7a9e54
Create Date: 2026-03-01 12:05:13.267760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '728c5cb63728'
down_revision: Union[str, None] = 'd83f1c7a9e54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sidequests', sa.Column('reward_xp', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sidequests', 'reward_xp')
    # ### end Alembic commands ###
