"""add_user_total_xp

Revision ID: d63ce93ed8bf
Revises: 728c5cb63728
Create Date: 2026-03-01 12:22:52.007773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd63ce93ed8bf'
down_revision: Union[str, None] = '728c5cb63728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('total_xp', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'total_xp')
    # ### end Alembic commands ###
