"""add_accepted_at_to_sidequests

Revision ID: f3ccc055a792
Revises: d63ce93ed8bf
Create Date: 2026-03-04 16:23:07.977659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3ccc055a792'
down_revision: Union[str, None] = 'd63ce93ed8bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sidequests', sa.Column('accepted_at', sa.DateTime(), nullable=True))
    op.execute("UPDATE sidequests SET accepted_at = created_at WHERE accepted_at IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sidequests', 'accepted_at')
    # ### end Alembic commands ###
