"""add_sidequest_reward_xp

Revision ID: c0c87c256a6d
Revises: d83f1c7a9e54
Create Date: 2026-03-01 11:55:16.207528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0c87c256a6d'
down_revision: Union[str, None] = 'd83f1c7a9e54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sidequests', sa.Column('reward_xp', sa.Integer(), nullable=False))
    op.create_check_constraint("check_reward_xp_positive", "sidequests", "reward_xp >= 1")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("check_reward_xp_positive", "sidequests", type_="check")
    op.drop_column('sidequests', 'reward_xp')
    # ### end Alembic commands ###
